### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [koma-4/FirstClass#1]
1. Зачем вам интерфейс `Main1`?
2. Классу лучше дать название, которое соответствует тому, что он делает. Название Main не самое лучшее. 
3. В выбранном вами способе представления графа исходящие дуги получать легко, а вот входящие очень сложно. Хотя и то  и другое довольно частая операция. Попробуйте что-то поменять, чтобы упростить получение входящих дуг. 
3. А почему Integer, а не int? [link](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L7)
4. Этот класс наследуется только от Object, так что в конструкторе вызывать конструктор предка (super) не нужно. [link](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L10)
5. А зачем `valueOf`? [link](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L15)
6. Если эти поля неизменяемы, то лучше их отметить как `final` (аналог val в kotlin). [link](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L6)
7. main можно отсюда убрать. [link](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L29)
8. Поправьте форматирование, а то всё поехало куда-то. [link](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L37)
9. При указании типа, как [здесь](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L27) и [здесь](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L33),  принято указывать наименее специфичный тип. В данном случае, это просто `Map`.
10. Может добавить конструктор, который позволяет создать пустой граф? 
11. Имена аргументов [здесь](https://github.com/koma-4/FirstClass/blob/068b730ee9a28eace6d07d6ce6b970b7ae92b87e/src/com/company/Main.java#L47) лучше поменять так, чтобы было понятно, из какой вершины и в какую будет дуга.

**Comment by koma-4** [comment]
1. Убрала переопределение и оставила getVertexMap без @Override 
2, 4, 5, 6, 7, 8, 9, 10, 12 исправила
3. Сделала теперь представление Графа через 2 Mapa. vertexMap остался без изменений, а vertexMap1 нужен для фиксации входящих дуг. Теперь метод получения входящих дуг работает быстрее
11. Не уверенна, что правильно Вас поняла. Но попыталась добавить такой метод

**Comment by Saloed** [comment]
1. Исходящие дуги это список, а входящие это множество? Как-то странно получается. Надо выбрать что-то одно и сделать одинаково. 
2. Для исходящих дуг вы храните ноду, в которую идёт дуга и вес. А для входящих только ноду. Тоже как-то странно получилось. 
2. `vertexMap` и `vertexMap1` не лучшие названия для этих полей. Одно хранит исходящие дуги, а другое входящие, но что есть что из названия не понятно и приходится вникать в код, чтобы это понять.
3. Старайтесь вообще не использовать числа в именах переменных, если это не предусмотрено описанием какого-то алгоритма. У вас такое встречается, например, [вот здесь](https://github.com/koma-4/FirstClass/blob/03b8c3c84d23f9cd76f37e9fb20c8b0295fc17d0/src/com/company/Graph.java#L47). 
4. А зачем в аргументе указывать пустое множество? [link](https://github.com/koma-4/FirstClass/blob/03b8c3c84d23f9cd76f37e9fb20c8b0295fc17d0/src/com/company/Graph.java#L49)
5. Для исходящих дуг вы спокойно изменяете список, который уже лежит в мапе. Для входящих вы зачем-то создаёте копию того множества, которое лежит. [link](https://github.com/koma-4/FirstClass/blob/03b8c3c84d23f9cd76f37e9fb20c8b0295fc17d0/src/com/company/Graph.java#L50)
6. Я не помню, что написано в задании, но было бы логично, если бы операции, которые возвращают входящие/исходящие дуги возвращали бы и вес. А то как-то странно получается. 
7. В операциях удаления и переименования, чтобы найти нужную дугу требуется перебрать все. Это нехорошо. Попробуйте придумать что-то ещё с представлением вершин и дуг. 
8. С методом для создания пустого графа получилось не очень. Смотрите. Вот я такой хочу создать граф. Я хочу создать сначала пустой граф, а потом добавлять в него вершины/дуги. Как это можно сделать у вас:
```java
/* 1
Мне нужно создавать мапы, которые являются частью вашего внутреннего представления. 
Нехорошо.
*/
var graph = new Graph(Map.of(), Map.of());

/* 2
С методом, который вы добавили, лучше не стало, 
поскольку чтобы его вызвать, нужно иметь созданный объект графа.
*/
var graph = new Graph(Map.of(), Map.of());
graph.EmptyGraphOf(List.of());

// Что хотелось бы
var graph = Graph.empty();
```
Такое можно сделать, если метод `empty` будет статическим. 

Ну и имена методов принято начинать с маленькой буквы. 

10. В тестах ещё актуально замечание 10 из предыдущего списка.

**Comment by koma-4** [comment]
1. Сделала теперь всё в списках
2. Теперь inVertexMap тоже хранит вес. Раньше не заносила вес, потому что в задании не требовалось в методах получения исходящих, входящих дуг выводить и их вес.
3, 4, 5, 10. Исправила
6. Убрала лишнее действие
7. Тоже исправила, изначально в задании было "получение списка исходящих из вершины дуг". Извиняюсь, я подумала получение их веса не требуется
8. При выборе способа реализации графа, я решила, что список смежности будет наилучшим решением, выбирая между списком и матрицей смежности. К сожалению, при такой реализации метод переименования вершин не очень хорош. Но они реализуются довольно не долго. Однако, такая реализация сильно выигрывает матрицу смежности в методе добавления новых вершин. Я руководствовалась тем, что этот метод используется чаще, чем переименование вершин. А метод удаления вершин в матрице, я полагаю, тоже не очень хорош. Поэтому я всё же считаю, что данное представление будет удобнее. Поправьте меня, пожалуйста, если я Вас неправильно поняла. 
Вчера весь день пыталась придумать что-то ещё и единственная полу-бредовая идея, которая хоть как-то смогла бы стать альтернативой была представить граф в виде строки вида "AB5,BC6" и в методах получения исходящих, входящих дуг, переименования вершин использовать регулярные выражения. Но мне кажется это совсем неудобное представление в отличие от исходного
9. Надеюсь, в этот раз я вас правильно поняла

**Comment by Saloed** [comment]
1. А почему [здесь](https://github.com/koma-4/FirstClass/blob/a7502d7ff4922c2cbbe4d9c6abbc6b3a8445074f/src/com/company/Graph.java#L56) недостаточно просто `remove`?
2. Замечание 6 из предыдущего списка.
3. Замечание 9 из первого списка.
4. Метод `remove` у мапы возвращает то, что удалил. Так что [вот такие места](https://github.com/koma-4/FirstClass/blob/a7502d7ff4922c2cbbe4d9c6abbc6b3a8445074f/src/com/company/Graph.java#L81) можно упростить.

**Comment by koma-4** [comment]
Всё поправила. В 1ом что-то я намудрила, Вы правы, достаточно `remove`

**Comment by Saloed** [comment]
1. Сейчас вы создаетё новую мапу, перекладываете в неё всё, что там уже лежало, добавляете в неё новую дугу и всё. Дальше с этой мапой ничего не происходит. Она никуда не кладётся, а просто теряется. Так что сейчас это работает неправильно. Я всё никак не могу понять, что вам мешает изменить ту мапу, которая уже лежит в `inVertexMap`? [link](https://github.com/koma-4/FirstClass/blob/f19a647f12ff07081c475fe4f6b95068d9395765/src/com/company/Graph.java#L48)
2. Если вы вызовете `remove`, когда там такого ключа нет, то он просто ничего не сделает. Так что проверку наличия ключа можно не делать. [link](https://github.com/koma-4/FirstClass/blob/f19a647f12ff07081c475fe4f6b95068d9395765/src/com/company/Graph.java#L56)
3. [Что-то странное тут происходит](https://github.com/koma-4/FirstClass/blob/f19a647f12ff07081c475fe4f6b95068d9395765/src/com/company/Graph.java#L89)
4. Судя по замечаниям 1 и 3, у вас в тестах как-то плохо проверяется, что там происходит с входящими дугами. Добавьте какой-то тест, который это проверит.
